
# $willAccountDeleted (bool) - true if the account will also be deleted
# $lastDueDate (date) - the last due date in the list
# $firstname (string) - Vorname
# $lastname (string) - Nachname
# $roleNumber (number) - the number of roles
# $roles (string) - a List generated by item generation (see below)
# $lastDeletionDate (date) - the last deletion date in the list
# $isEmeriti (bool) - true if the person is emeriti
# $isProf (bool) - true if the person is a professor
# $accountDeletitionDate (date) the date when account will deleted
notification-staff=


{$accountDeletitionDate}

  {$isEmeriti ->
    [true] In {TIMESPAN(NOW(), $lastDeletionDate,"Dativ")}, am {$lastDeletionDate} werden wir in Absprache mit Ihrer Fachbereichsleitung Ihre Berechtigungen entsprechend Ihres Status als Pro a.D. anpassen.
    *[false]   {$willAccountDeleted ->
                  [true]  { COMPARE($accountDeletitionDate, $lastDeletionDate) ->
                            [0]   { $isProf ->
                                    [true]  Wenn Sie nichts unternehmen, 
                                    *[other] Daher
                                  } wird Ihre Hochschulkennung {$accountDeletitionDate}in {TIMESPAN(NOW(), $lastDeletionDate,"Dativ")}, am {$lastDeletionDate}, deaktiviert. Sie erhalten hierzu noch eine gesonderte E-Mail.
                            *[other]  { $isProf ->
                                        [true]  Wenn Sie nichts unternehmen, 
                                        *[other] Daher
                                      } verlieren Sie die Berechtigungen, die mit Ihrer Beschäftigung verknüpft waren. Ihre Hochschulkennung bleibt jedoch bis zum {$accountDeletitionDate} ({TIMESPAN(NOW(), $accountDeletitionDate,"Akkusativ")}) erhalten.

                          }
                  *[other] Sie verlieren die Berechtigungen, die mit Ihrer Beschäftigung verknüpft waren. Ihre Hochschulkennung bleibt jedoch zunächst erhalten.
                           
                }
  } 

